.PHONY: all
all:
	dcraw -v -4 -o 0 -h -W -T -H 1 -b 3 ektar100_it8_30m_cp80c_triband.NEF
	dcraw -v -4 -o 0 -h -W -T -H 1 -b 3 ektar100_it8_30m_cp80c_triband_bp470.NEF
	dcraw -v -4 -o 0 -h -W -T -H 1 -b 3 ektar100_it8_30m_cp80c_triband_bp525.NEF
	dcraw -v -4 -o 0 -h -W -T -H 1 -b 3 ektar100_it8_30m_cp80c_triband_lp610.NEF
